#server:
#  port: 8088
#
#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2
#  datasource:
#    url: jdbc:h2:~/room-hospital
#    username: sa
#    password:
#    driverClassName: org.h2.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update
#  application:
#    name: ROOM-SERVICE
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
