server:
  port: 8091

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:~/login
    username: sa
    password:
    driverClassName: org.h2.Driver
    initialization-mode: always


  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

  application:
    name: LOGIN-SERVICE

bezkoder:
  app:
    jwtSecret : bezKoderSecretKey
    jwtExpirationMs : 86400000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true


#spring:
#  datasource:
#    url: jdbc:mysql://${DB_SERVER}:${DB_PORT:3306}/${DB_NAME}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#  application:
#    name: JWT-AUTH-SERVICE

#eureka:
##  instance:
##    preferIpAddress: true
##    hostname: eureka-0
#  client:
#    register-with-eureka: true
#    fetch-registry: true
##    serviceUrl:
##      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka

#bezkoder:
#  app:
#    jwtSecret : bezKoderSecretKey
#    jwtExpirationMs : 86400000
