INSERT INTO ROLE (id,name) VALUES (1, 'ROLE_USER');
INSERT INTO ROLE (id,name) VALUES (2, 'ROLE_DOCTOR');
INSERT INTO ROLE (id,name) VALUES (3, 'ROLE_LABTECHNICIAN');
INSERT INTO ROLE (id,name) VALUES (4, 'ROLE_ADMIN');

